### PR TITLE
Adding cond_put_or_create operation.

### PR DESCRIPTION
**Pull request by jsdt**
Put succeeds if the conditions are satisfied or the object doesn't exist.  The only server-side change was removing a condition in common/key_change.cc which should not be reached by any other operation.

### CODE REVIEW

**Comment by HarryR** [comment]
So many syntax changes changes in `bindings/go/client/client.go`

also in common/key_change.cc the removal of that condition worries me because I think it would break `cond_put`

Because of that removal the `cond_put` acts exactly the same as the new `cond_put_or_create`.

**Comment by jsdt** [comment]
I generated the client bindings by running the python scripts in bindings/. Is there a different way that they are supposed to be generated?

I can see why you might be worried, but the case that I deleted is not reached by any other operation.  If the key does not exist, a cond_put would hit the previous condition first (!has_old_value && kc->fail_if_not_found).

**Comment by HarryR** [comment]
Ah I see what you mean now.

   `cond_put` has `false, true,  false`
   `cond_put_or_create` has `false, false, false`

Re:
    bool erase;
    bool fail_if_not_found;
    bool fail_if_found;

That looks reasonable.

**Comment by jsdt** [comment]
I haven't run the test suite, I just did some manual tests of cond_put and cond_put_or_create.

It can be used for operations like "update this record unless a version with a newer timestamp is already there."
You could accomplish that with a put_if_not_exists, then a cond_put if that fails, but that is potentially less efficient.  The reason I want it is a bit esoteric, but using put_if_not_exists and cond_put can lead to starvation if the record is always created by another process before put_if_not_exists is called, and always deleted by another process before cond_put is called.

**Comment by HarryR** [comment]
Anything which prevents starvation or additional roundtrips is a good thing IMO, it's a good equivalent to MySQL's INSERT OR UPDATE.

Seeing as this is a small change that fits neatly and logically with the other SET operations I think it'd be reasonable for this included in HyperDex.

**Comment by kaimast** [comment]
This looks good to me, but you should definitely add tests to the pull request.

**Comment by jsdt** [comment]
It looks like adding tests would mean adding a section in doc/atomic-ops.tex.  Is that correct?

**Comment by rescrv** [comment]
If you add some tests to ``doc/atomic-ops.tex`` and run ``make maintainer-generate``, you'll get the tests to be run with ``make check``.

Also, we probably need to adjust this part of the diff, if tests fail anywhere else:

```diff
diff --git a/common/key_change.cc b/common/key_change.cc
index 071cc43..88a6e6c 100644
--- a/common/key_change.cc
+++ b/common/key_change.cc
@@ -86,10 +86,6 @@ key_change :: check(const schema& sc,
     {
         return NET_NOTFOUND;
     }
-    else if (!has_old_value && !kc->checks.empty())
-    {
-        return NET_CMPFAIL;
-    }
     else if (has_old_value && kc->fail_if_found)
     {
         return NET_CMPFAIL;
```

With the tests present and passing, I'd be happy to merge this request.  It looks like a great feature.

**Comment by jsdt** [comment]
I added tests, and make check passed (though I only used --enable-python-bindings).

I fixed the go client formatting changes, but the generating scripts should probably call gofmt -w.

**Comment by rescrv** [comment]
Thank you!

**Pull request merged**
